version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mon-php-app
    volumes:
      - ./projet-motus:/var/www/html
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    container_name: mon-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: motus
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mon-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data: